webtalk_init -webtalk_dir C:/Users/buenting/cpre4880/labs/mp-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_axi_ppm_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 17 15:49:05 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174156856_1777588437_210796650_422" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7f1ed925-5bc7-44c3-a33a-1bd311d17516" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "65ecd6645bd849eeb03cf551c449b869" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "58" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 7 265" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2381 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2280262649 -regid "174156856_1777588437_210796650_422" -xml C:/Users/buenting/cpre4880/labs/mp-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_axi_ppm_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/buenting/cpre4880/labs/mp-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_axi_ppm_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/buenting/cpre4880/labs/mp-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_axi_ppm_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
